import type { Metadata } from "next";
import "./global.css";
import { AppProvider } from "@/contexts/application.context";

export const metadata: Metadata = {
  title: "Library Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <body>{children}</body>
      </AppProvider>
    </html>
  );
}
